version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22.9.0
    commands:
      - npm install

  build:
    commands:
      - npm run build
      - zip -r app.zip dist/

artifacts:
  files:
    - app.zip
  name: app-artifact
  discard-paths: yes
